[FEAT] CategoryContents View 세부 기능 추가하기 (#26)
TeamHavit/Havit-iOS pull request #56
Opened 2022-01-15 05:04 UTC by beansbin

## 🟣 관련 이슈
- #26

## 🟣 구현/변경 사항 및 이유
 : CategoryContentsView 레이아웃 세부 기능 추가
 * DropDown 메뉴 구현 : BTNavigationDropDownMenu 라이브러리 설치
 * 토스트 메시지 구현 : UIComponents 의 ToastAlarm()
 * Bottom Panel 구현하기 (정렬, 더보기) : MaterialBottomPanel 라이브러리 설치
 * CategoryContetnsCoordinator 생성

## 🟣 PR Point
 * CocoaPods를 사용해서 앞으로는 하얀색 파일에서 작업하셔야 합니다..ㅎㅎ
 * 기능 명세서대로 searchBar 스크롤 가능하게 + 드롭다운 구현했으나 BT 라이브러리를 뜯었어여. 그래서 아직 고친 pod은 커밋되지 않은 상태라서.. pod file을 .gitignore에서 뺄지, 아니면 프로젝트로 형식으로 import할지? 여러분과 논의를 해보고 싶슴당😀
 <details>
<summary>참고로 라이브러리를 뜯을 수 밖에 없었던 저의 삽질기가 궁금하시다면.. click</summary>
<div markdown="1">       
1. DropDown 라이브러리
 * 네비게이션바에 특화된 dropdown이 아닌 정말 웹에서의 그 드롭다운메뉴 라이브러리.      
  
![스크린샷 2022-01-13 오후 7 34 25](https://user-images.githubusercontent.com/46108770/149609395-60568cf8-817a-4eff-ac56-1983a8f0b3d4.png) 
 * 서치바가 네비게이션에 붙어있어서 드롭다운 메뉴가 나타날 때 서치바도 같이 나타나는 문제.      
 * 네비게이션바에 못 붙이고 꼼수로 그 아래 view에 붙여서 대충 위치를 잡았지만 스크롤해서 서치바가 사라져도 원래 자리에 그대로 붙어있는 문제.
 

2. 서치바 네비게이션에 안 넣고 그냥 바탕 뷰에 붙여버림
 : 드롭다운할 때 서치바가 가려지기는 하지만 스크롤될 때 사라지는 건 네비게이션에 있을 때만 가능함.

3. BTNavigationDropDownMenu
 * 네비게이션에 붙이는 라이브러리라서 눌렀을 때 바탕이 흐려진다거나 하는 부분이 잘 되있음
 * 네비게이션에 붙이는 방식이다보니 얘도 서치바가 네비게이션에 붙어있음 드롭다운 메뉴 나타났을 때 서치바도 안 없어짐.
 * 그냥 hidden 시켜버릴래도 서치바 높이가 애매하게 스크롤되는 경우가 존재함 --;
  => 해결 : dropDownMenu만들 때 현재 뷰컨 같이 넘겨주고 -> show()될 때 현재 서치바 높이 만큼 빼준 위치에 dropDown 보이도록 함.
```swift
if #available(iOS 11.0, *) {
            self.menuWrapper.frame.origin.y = self.navigationController!.navigationBar.frame.maxY - (self.viewController.navigationItem.searchController?.searchBar.frame.height)!
        } else {
            // Fallback on earlier versions
        }
```

</div>
</details>

## 🟣 참고 사항
* 디자인 적용 안된 상태이니 참고해주세요~! 컬렉션뷰셀 레이아웃도 폰트 적용하면서 세부적으로 조정할 예정입니당

![화면 기록 2022-01-15 오후 2 02 20](https://user-images.githubusercontent.com/46108770/149609712-80a71ef1-c137-4862-9db5-793400cf1e97.gif)

2022-01-15 05:20 UTC, YoonAh-dev commented
@beansbin 
아직 build test에 pod부분이 반영이 안되어있어서 fail나는거니깐 신경쓰지마세요~

2022-01-15 05:31 UTC, noah0316 commented
@beansbin 
예빈 선배 혹시 git hook `git config core.hookspath .githooks`가 적용되어있을까요??

2022-01-15 06:25 UTC, Suyeon9911 reviewed
폰트와 에셋이 추가되었으니 전체적으로 적용해주시면 될것 같습니다!

2022-01-15 06:25 UTC, Suyeon9911 commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
>          filterView.addSubview(sortButton)
Extension에 있는 addSubViews 를 사용해 한번에 올려주는게 좋은 방법 같아보여용 !

2022-01-15 06:29 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
>          filterView.addSubview(sortButton)
superview에는 되는데 filterView에는 addSubViews가 적용이 안되더라구여... 그래서 저렇게 뺐습니당!

2022-01-15 06:38 UTC, sujinnaljin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        button.addTarget(self, action: #selector(showSortBottomSheet(_:)), for: .touchUpInside)
p5;
.rx.tap 을 사용할 수 있을거 같아욤

2022-01-15 06:40 UTC, sujinnaljin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        navigationController?.setNavigationBarHidden(false, animated: false)
p4
nav 가 없는 곳에서 pop 해서 돌아올때 nav 가 사라지는 현상이 있어서 이 코드를 여기에 써주신건가요?

2022-01-15 06:41 UTC, sujinnaljin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        self.navigationItem.rightBarButtonItem = navigationRightButton
p5;
self 쓸거면 일관되게 다 적용하거나 다 적용하지 않는건 어덜까요?

2022-01-15 06:42 UTC, sujinnaljin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        searchController.hidesNavigationBarDuringPresentation = false
p1;
hidesNavigationBarDuringPresentation = false 가 생성자 쪽에 정의되어있는데 중복되는 코드지 않을까요?

2022-01-15 06:43 UTC, sujinnaljin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        let vc = SortBottomSheetViewController()
p1;
약어 쓰지 말고 의미 있는 변수명을 짓도록 합시다

2022-01-15 06:43 UTC, sujinnaljin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        let bottomSheet: MDCBottomSheetController = MDCBottomSheetController(contentViewController: vc)
p5;
Sheet 로 끝나면 그냥 View 인것 같아서 Controller 까지 붙여보는건 어떨가요?

2022-01-15 06:44 UTC, sujinnaljin commented on Havit/Havit/Screens/CategoryContents/View/MoreBottomSheetViewController.swift
> +let moreList = ["제목 수정", "공유", "카테고리 이동"]
class 안에 넣어주세요

2022-01-15 06:45 UTC, sujinnaljin commented on Havit/Havit/Screens/CategoryContents/View/SortBottomSheetViewController.swift
> +let sortList = ["최신순", "과거순", "최근 조회순"]
p1;
class 안에 넣어주세요

2022-01-15 06:45 UTC, sujinnaljin commented on Havit/Havit/Screens/CategoryContents/View/SortBottomSheetViewController.swift
> +            $0.leading.top.trailing.equalTo(view)
p4;
bottom 이나 height 를 잡아야하지 않을까여??

2022-01-15 06:46 UTC, sujinnaljin commented
예빈님 한번에 작업하시는 양이 많아서 코드리뷰 하기 조금 어려운 부분이 있습니다
앞으로 기능을 더 잘게 나눠서 pr 올려주시면 리뷰어 분들의 부담이 줄어들 것 같아요

2022-01-15 06:56 UTC, sujinnaljin commented
제 의견은~~~~~ 저거 그냥 기본 action sheet 로 구현해야할것 같다고하고~~~~ 나중에 custom 으로 만들기~~!!

2022-01-15 07:06 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        navigationController?.setNavigationBarHidden(false, animated: false)
네비게이션바가 hidden 처리되어있어서 표시하기 위해 작성했습니다!

2022-01-15 07:11 UTC, sujinnaljin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        navigationController?.setNavigationBarHidden(false, animated: false)
오잉 최신 baseViewController 가 변경되었느데도  동일한가요?? 신기하네영

2022-01-15 07:12 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/SortBottomSheetViewController.swift
> +            $0.leading.top.trailing.equalTo(view)
UILabel()의 경우에는 height가 text에 따라 달라지는 걸로 알고 있어서 안 잡았는데 아닌가여 ,,?!!!

2022-01-15 07:12 UTC, sujinnaljin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        case Sort1, Sort2, Sort3
p1;
case 명은 소문자로 시작합니다 . 그리고 의미있는 이름을 지어주세요

2022-01-15 07:13 UTC, sujinnaljin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        case Sort1, Sort2, Sort3
enum 이름은 SortType 등이 어떨까요?

2022-01-15 07:14 UTC, sujinnaljin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        case Sort1, Sort2, Sort3
예빈님 빌드 phase 때 린트랑 precommit 둘다 적용 안되어있나요? 왜 자꾸 요런 린트 에러뜨는 커밋들이 올라올까요?

2022-01-15 07:14 UTC, sujinnaljin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +                let cell: SortThreeContentsCollectionViewCell = collectionView.dequeueReusableCell(withReuseIdentifier: SortThreeContentsCollectionViewCell.className, for: indexPath) as! SortThreeCon
p1;
forcasting 지양해주세요

2022-01-15 07:15 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        self.navigationItem.rightBarButtonItem = navigationRightButton
수정했습니다!
반영 커밋 : c1ae51

2022-01-15 07:15 UTC, sujinnaljin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +                let cell: SortThreeContentsCollectionViewCell = collectionView.dequeueReusableCell(withReuseIdentifier: SortThreeContentsCollectionViewCell.className, for: indexPath) as! SortThreeCon
그리고 저거 캐스팅안해도 저희가 정의해놓음 함수 쓰면 앞에 
let cell: SortThreeContentsCollectionViewCell
요렇게 캐스팅 명시해준것만으로 충분하지 않나여??

2022-01-15 07:16 UTC, sujinnaljin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +            print("?????????")
p1;
logger 구현되어있지 않나요 저희?

2022-01-15 07:16 UTC, sujinnaljin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +    var sortNum: ShowSort = ShowSort.Sort1
p1;
이름!!!!!!!!!!

2022-01-15 07:17 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        searchController.hidesNavigationBarDuringPresentation = false
수정했습니다!
반영 커밋 : c1ae51

2022-01-15 07:17 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        let vc = SortBottomSheetViewController()
수정했습니다!
반영 커밋 : c1ae51

2022-01-15 07:17 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        let bottomSheet: MDCBottomSheetController = MDCBottomSheetController(contentViewController: vc)
수정했습니다!
반영 커밋 : c1ae51

2022-01-15 07:17 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/MoreBottomSheetViewController.swift
> +let moreList = ["제목 수정", "공유", "카테고리 이동"]
수정했습니다!
반영 커밋 : c1ae51

2022-01-15 07:17 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/SortBottomSheetViewController.swift
> +let sortList = ["최신순", "과거순", "최근 조회순"]
수정했습니다!
반영 커밋 : c1ae51

2022-01-15 07:17 UTC, Suyeon9911 commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
>          filterView.addSubview(sortButton)
@beansbin 넵 ~~ PR 날릴때  viewcontroller 이나 cell 단위로 끊어서 디자인 작업까지 한번에 하시면 보기에도 편하고 ... 다시 작업할 필요도 없고... 커밋수도 줄어들것같습니다 ! 개인적인 의견입니..당 ><...

2022-01-15 07:19 UTC, sujinnaljin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        searchController.hidesNavigationBarDuringPresentation = false
선생님 커밋 링크가 안대여

2022-01-15 07:20 UTC, sujinnaljin commented on Havit/Havit/Screens/CategoryContents/View/SortBottomSheetViewController.swift
> +            $0.leading.top.trailing.equalTo(view)
고건 맞긴 한데 bottom 도 안잡아도 되나요?? 걍 끝없이 늘어나는 앤가요?? 그럼 superview를 넘어갈 상황은 없나요???

2022-01-15 07:23 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/SortBottomSheetViewController.swift
> +            $0.leading.top.trailing.equalTo(view)
그 밑에 tableView가 titleLabel을 top으로 잡고 있어서 필요 없지 않을까 그리고 한줄짜리 고정된 타이틀이라서 안잡아도 생각하긴 했습니닷..

2022-01-15 07:24 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +                let cell: SortThreeContentsCollectionViewCell = collectionView.dequeueReusableCell(withReuseIdentifier: SortThreeContentsCollectionViewCell.className, for: indexPath) as! SortThreeCon
맞습니당.. 맞습니당.. 컬렉션뷰 변경하는거 구현하다고 요거 쓰고 저거 쓰고 해보다가 남겨두게됐네요..!! 변경하겠습니다!!

2022-01-15 07:25 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +            print("?????????")
구현되어있습니닷! 잠깐 쓰고 지운다는게......😂

2022-01-15 07:25 UTC, sujinnaljin commented on Havit/Havit/Screens/CategoryContents/View/SortBottomSheetViewController.swift
> +            $0.leading.top.trailing.equalTo(view)
그렇다기에 tableView의 height 에 따라 titleLabel 이 가변적이라기엔 , tableView의 bottom 이 잡혀있지 않은것 같습니다?? 이런거 에러 안뜨나요?? 제가 잘못이해하고 있는걸까요

2022-01-15 07:26 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/SortBottomSheetViewController.swift
> +            $0.leading.top.trailing.equalTo(view)
엉엉 제가 다시 한번 확인해보겠습니다 레이아웃만 잡아놓고 세부적인건 디자인 적용하고 수정하려고 했음다...!!!

2022-01-15 07:36 UTC, YoonAh-dev commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
>          filterView.addSubview(sortButton)
@beansbin 
UIView+Extension으로 넣어놨기 때문에 addSubViews가 안먹을리가 없어요!!!!!🌝

2022-01-15 07:37 UTC, YoonAh-dev commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        navigationController?.setNavigationBarHidden(false, animated: false)
@beansbin 
혹시 configUI에서 super.configUI() 안하셨나요? 
제가 BaseViewController에 이미 false을 해둬서 적용이 안될리가 없어요!!

2022-01-15 07:42 UTC, YoonAh-dev commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        case Sort1, Sort2, Sort3
@beansbin 
린트가 local에는 적용이 안되어있는거 같아요!
README에 noah님이 적용 방법을 올려뒀습니다. 적용해주시면 좋을 거 같아요!

2022-01-15 07:45 UTC, YoonAh-dev commented on Havit/Havit/Global/UIComponent/ContentsCollectionViewCell.swift
> +     var mainImageView: UIImageView = {
p3;

해당 Cell에 있는 property를 밖에서 접근할 필요가 없다면 private으로 적용해주는 게 좋을 거 같아요!

2022-01-15 07:49 UTC, YoonAh-dev commented on Havit/Havit/Global/UIComponent/ToastAlarm.swift
> +        let toastLabel = UILabel(frame: CGRect(x: controller.view.frame.size.width/2 - 75,
빈스빈님 혹시 toastLabel에 정해진 위치랑 width, height가 있는 이유가 있을까요?

2022-01-15 07:50 UTC, YoonAh-dev commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +            $0.top.equalTo(view.safeAreaLayoutGuide.snp.top)
```suggestion
            $0.leading.bottom.trailing.top.equalTo(view.safeAreaLayoutGuide)
```
이렇게 사용 가능합니다!

2022-01-15 07:52 UTC, YoonAh-dev commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
>              $0.leading.trailing.equalTo(mainView).offset(0)
p1;

offset이 0일때는 offset를 써주지 않아도 딱맞게 적용됩니다!
offset(0)인 부분은 전체적으로 없애주시면 좋겠습니다!

2022-01-15 07:54 UTC, YoonAh-dev commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +    }
예빈님 혹시 String타입으로 enum의 rawValue를 잡은 이유가 있을까요?

2022-01-15 07:57 UTC, YoonAh-dev commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        present(bottomSheet, animated: true, completion: nil)
p5;

라이브러리가 SheetViewController를 present하는 방식으로 구현하는거라면 SheetViewController라는 ViewController를 만들어서 BottomSheet를 직접 구현하는게 더 좋지 않을까 하는 마음이 쬐깐 있습니다.!
그러면 BottomSheet관련 라이브러리를 사용하지 않고 동일한 방식으로 BottomSheet를 구현할 수 있을 거 같아요..! ViewController하나만 만들면 되는데 라이브러리까지 도입한 거 같아서 나중에라도 직접 구현해보시면 어떨까하는 조꾸만한 마음..💜

2022-01-15 08:02 UTC, YoonAh-dev commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        }
p5;

Sort Enum의 rawValue를 Int타입으로 한다면 이 부분을 조금 더 효율적인 방식으로 구현할 수 있지 않을까 싶습니다.

지금 나올 수 있는 상황은 sort1, sort2, sort3인데, 이를 0, 1, 2로 생각하면
sortNum % 3 인 값이 
* 0 -> sort 1
* 1 ->  sort 2
* 2 ->  sort 3
이렇게 되기 때문에 우리는 터치이벤트가 발생하면 sortNum + 1만 해주면 굳이 sortNum에 case마다 값을 넣어주지 않아도 되지 않을까.. 싶습니다!

2022-01-15 08:03 UTC, YoonAh-dev commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        }
p3;

register가 터치 이벤트마다 일어나서 이미 register된 셀도 또 register되는 문제가 일어나지 않을까요?

2022-01-15 08:04 UTC, YoonAh-dev commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +            }
p4;

이 부분도 switch로 정리하면 한 눈에 보일 거 같아요!

2022-01-15 08:05 UTC, YoonAh-dev commented on Havit/Havit/Screens/CategoryContents/View/Cell/MoreBottomSheetTableViewCell.swift
> +import UIKit
p1;

snapkit를 사용했는데 import가 안되어 있어요!

2022-01-15 08:06 UTC, YoonAh-dev commented on Havit/Havit/Screens/CategoryContents/View/Cell/MoreBottomSheetTableViewCell.swift
> +    var label: UILabel = UILabel()
p2;

cell 내부에서만 쓰는 property는 private으로 적용해주시면 해당 property가 다른 곳에서 사용되는지 , 어느정도의 접근레벨을 가졌는지 확인하기 좋지 않을까 하는 마음입니당

2022-01-15 08:06 UTC, YoonAh-dev commented on Havit/Havit/Screens/CategoryContents/View/Cell/MoreBottomSheetTableViewCell.swift
> +        contentView.addSubview(label)
p1;

addSubViews([])로 묶어주세요!

2022-01-15 08:09 UTC, YoonAh-dev commented on Havit/Havit/Screens/CategoryContents/View/Cell/MoreBottomSheetTableViewCell.swift
> +            $0.leading.equalTo(contentView).offset(16)
p1;

contentView가 superView로 생각이 되어서 다는 코멘트입니당. 혹시 아니라면 무시해주세요..🙄
현재 content를 기준으로 안쪽으로 offset를 잡고 있기 때문에 offset보다는 inset를 사용하는게 적합할 거 같습니다.

또한, 현재 잡아두신 레이아웃을 보면 top, bottom 모두 offset이 10으로 되어있는데, bottom은 offset이 10이면 현재 셀 밖으로 10정도 나간 레이아웃인 거 같습니다. 안쪽으로 10을 잡고 싶다면 offset(-10), inset(10)이 맞습니다. 의도한 것이 아니라면 변경해주세요!

2022-01-15 08:11 UTC, YoonAh-dev commented on Havit/Havit/Screens/CategoryContents/View/Cell/SortThreeContentsCollectionViewCell.swift
>          contentView.addSubViews([mainImageView, titleLabel, subtitleLabel, dateLabel, linkLabel, alarmLabel, moreButton, isReadImageView])
여기서는 잘 써주셨어요👍
요것처럼 써주시면 됩니다!!

2022-01-15 08:13 UTC, YoonAh-dev commented on Havit/Havit/Screens/CategoryContents/View/MoreBottomSheetViewController.swift
> +        tableView.register(cell: MoreBottomSheetTableViewCell.self, forCellReuseIdentifier: MoreBottomSheetTableViewCell.className)
p1;

`tableView.register(cell: )`여기까지만 써도 사용할 수 있게 Extension으로 넣어뒀습니다. 이 형식으로 변경해주세요!

2022-01-15 08:15 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
>          filterView.addSubview(sortButton)
오류가 나서 밖으로 뺀거였는데..😧 다시 한번 해보겠습니당 !! 제가 뭘 잘못 적용했나봐여

2022-01-15 08:16 UTC, YoonAh-dev commented on Havit/Havit/Screens/CategoryContents/View/MoreBottomSheetViewController.swift
> +    }
p2;

외부에서 해당 함수를 사용하지 않을 거 같아요!
private으로 수정하는 건 어떠신가요?

2022-01-15 08:16 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
>          filterView.addSubview(sortButton)
@Suyeon9911 오홍 꿀팁 감사합니다!! 적용해보도록 할게요😊😊

2022-01-15 08:20 UTC, YoonAh-dev commented on Havit/Havit/Screens/CategoryContents/View/MoreBottomSheetViewController.swift
> +        return 3
p1;

위에 list를 만들어두셨던데 list.count로 설정하는거 어떠신가요!

2022-01-15 08:21 UTC, YoonAh-dev commented on Havit/Havit/Screens/CategoryContents/View/SortBottomSheetViewController.swift
> +        return 3
p1;

여기도 list.count로 잡아주세요!

2022-01-15 09:26 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        navigationController?.setNavigationBarHidden(false, animated: false)
이전에 작성해둔 코드라서 변경을 안 해둔 것 같습니다~! 지금 수정하니 제대로 동작하네요 😃

2022-01-15 09:28 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        case Sort1, Sort2, Sort3
수정했씁니다 :> 린트 아직 적용하지 않아서 뜨는 오류인 것 같습니당 :>

2022-01-15 09:37 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +                let cell: SortThreeContentsCollectionViewCell = collectionView.dequeueReusableCell(withReuseIdentifier: SortThreeContentsCollectionViewCell.className, for: indexPath) as! SortThreeCon
수정했습니닷!!!

2022-01-15 09:37 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +            print("?????????")
맞습니다 홀랑 지울라 했는데 남아버렸네요 ...ㅎㅎㅎ

2022-01-15 09:38 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +    var sortNum: ShowSort = ShowSort.Sort1
수정했습니다 !!

2022-01-15 09:41 UTC, beansbin commented on Havit/Havit/Global/UIComponent/ContentsCollectionViewCell.swift
> +     var mainImageView: UIImageView = {
수정했습니다!!!

2022-01-15 09:43 UTC, beansbin commented on Havit/Havit/Global/UIComponent/ToastAlarm.swift
> +        let toastLabel = UILabel(frame: CGRect(x: controller.view.frame.size.width/2 - 75,
카테고리 컨텐츠 뷰 기준으로 대략의 위치를 잡았는데 좀 더 확장성을 위해서 파라미터로 width, height,  위치를 받게 수정할 수도 있을 것 같습니당!

2022-01-15 09:45 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +            $0.top.equalTo(view.safeAreaLayoutGuide.snp.top)
수정했습니다 !!!

2022-01-15 09:46 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
>              $0.leading.trailing.equalTo(mainView).offset(0)
수정했습니다!!! :)

2022-01-15 09:47 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +    }
쓸려다가 안쓴채로 남아있었네요 수정했씁니다!!!!!

2022-01-15 09:49 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        present(bottomSheet, animated: true, completion: nil)
이전에 뷰 컨트롤러가 올라오는 높이 조절이 안됐던 기억이 있어서 라이브러리 사용을 했는데.. 나중에 여유되면 다시 찾아서 구현해보겠씁니다!!
그리고 이 부분은 수진님 코리대로 액션 시트를 커스텀하는 방식으로 변경할 것 같습니다...!!!!

2022-01-15 09:49 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/Cell/MoreBottomSheetTableViewCell.swift
> +    var label: UILabel = UILabel()
넵 적용했습니다!!! :>

2022-01-15 09:50 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/Cell/SortThreeContentsCollectionViewCell.swift
>          contentView.addSubViews([mainImageView, titleLabel, subtitleLabel, dateLabel, linkLabel, alarmLabel, moreButton, isReadImageView])
넵 감사합니다~~ :>!!!

2022-01-15 09:56 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        }
나중에 리팩토링하는 방향으로 수정하겠습니다 ! :> 좋은 리뷰 감사합니다

2022-01-15 09:57 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        }
contentCollectionView 하나에  register 하는 방식이라서 별 문제 없을 거라고 생각했는데요.. 😀 혹시 아닌걸까요 ?? ㅠㅠ

2022-01-15 09:59 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +            }
뭔가 중복 스위치문을 쓰면 안될 것 같아서 if문으로 썼었습니닷.. !! 변경했씁니다!!!!

2022-01-15 09:59 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/Cell/MoreBottomSheetTableViewCell.swift
> +import UIKit
import 했습니닷!!

2022-01-15 10:01 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/Cell/MoreBottomSheetTableViewCell.swift
> +        contentView.addSubview(label)
수정했씁니다!!!

2022-01-15 10:37 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/Cell/MoreBottomSheetTableViewCell.swift
> +            $0.leading.equalTo(contentView).offset(16)
넵 적용했습니다~!!!!!

2022-01-15 10:38 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/MoreBottomSheetViewController.swift
> +    }
다른 파일도 함께 수정해두었습니다!! :>

2022-01-15 10:39 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/MoreBottomSheetViewController.swift
> +        return 3
설정해두었습니다 !!! :)

2022-01-15 10:40 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/SortBottomSheetViewController.swift
> +        return 3
넵 마찬가지로 수정해두었씁니다~!~!

2022-01-15 10:41 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/MoreBottomSheetViewController.swift
> +        tableView.register(cell: MoreBottomSheetTableViewCell.self, forCellReuseIdentifier: MoreBottomSheetTableViewCell.className)
넵 함수 변경해서 수정해두었씁니다!! :>

2022-01-15 17:48 UTC, sujinnaljin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +                let cell: SortThreeContentsCollectionViewCell = collectionView.dequeueReusableCell(withReuseIdentifier: SortThreeContentsCollectionViewCell.className, for: indexPath) as! SortThreeCon
예빈님 수정하시면 수정했다고 말씀주시는것보다 커밋번호를 남겨주시는게 좋을 것 같습니다~

2022-01-15 17:52 UTC, sujinnaljin commented on Havit/Havit/Coordinator/AppCoordinator.swift
> +        let coordinator = CategoryContentsCoordinator(navigationController: navigationController)
예빈님걸 기본으로 시작하게 테스트해두신걸 변경안한것 같습니다

2022-01-15 17:54 UTC, sujinnaljin commented
코드리뷰 변경사항에 대해서 커밋번호를 남겨주지 않으시면, 리뷰어가 처음부터 예빈님 파일을 다 봐야하는 이슈가 있습니다. 커밋번호를 남겨주세요.
그리고 레이아웃을 일단 대충만 잡아놓으신것 같은데, 리뷰어는 이게 제대로 된건지, 나중에 고칠 예정이시라 대충 처리해놓으신건지 알기 어렵고 의미있는 리뷰를 하기 어려워집니다. 따라서 제대로 구현해주신 사항에 대해서만 커밋 및 pr 날려주시면 좋을 것 같습니다.

2022-01-15 17:57 UTC, sujinnaljin commented on Havit/Havit/Coordinator/CategoryContentsCooridnator.swift
> +        case .main:
p5;
뒤로 가야하는건 previous 정도의 네이밍은 어떠신가여??
수연님께도 말씀 드린 부분이긴 합니다만, 저도 이 부분에 대해 고민했는데, category content -> main category 의 flow 가 아닐 수도 있고, 어디서 나타나는 애인지 관리하기도 어려우니 저는 .previous 정도의 case 로 pop 을 처리했습니다. 
참고만 해주세여~

2022-01-15 17:58 UTC, sujinnaljin commented on Havit/Havit/Global/UIComponent/ContentsCollectionViewCell.swift
> +     private var mainImageView: UIImageView = {
p1;
let 으로 선언해도 무방할듯합니다

2022-01-15 18:02 UTC, sujinnaljin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        case sort1, sort2, sort3
p1;
의미있는 이름을 지어주세요 sort1, sort2, sort3 이 뭔지 알 수 없습니다

2022-01-15 18:02 UTC, sujinnaljin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +    var sortNum: SortType = .sort1
p1;
이름 변경이 되지 않은 것 같습니다. sortNum 가 뭘까요?

2022-01-15 18:04 UTC, sujinnaljin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        super.viewWillAppear(animated)
이건 왜 따로 사용하신걸까요?

2022-01-15 18:05 UTC, sujinnaljin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
>      func setNavigationItems() {
p5;
s 가 없는게 더 적당할것 같습니다~

2022-01-15 18:05 UTC, sujinnaljin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +           let view = UIView(frame: CGRect(x: 8.0, y: 8.0, width: actionSheet.view.bounds.size.width - 8.0 * 4.5, height: 120.0))
p5; 
정렬,,??

2022-01-15 18:06 UTC, sujinnaljin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        print("change!")
p5;
나중에 잊지말고 삭제해주세여

2022-01-15 18:13 UTC, sujinnaljin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        present(bottomSheet, animated: true, completion: nil)
앗 제가 말씀드린건 BT 어쩌구 써서 navigation bar 에서 내려오는 부분을 말씀드리긴 한거였는데,,!!!

2022-01-15 18:16 UTC, sujinnaljin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        }
음 이 부분을 리팩토링하는 방식은 네이밍 수정 완료해주시면 다시 보겠습니당

2022-01-16 13:00 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        case sort1, sort2, sort3
저도 이 부분 네이밍에 대해서 많이 고민을 했었는데요.. 제플린에서 뷰 이름을 정렬1, 정렬2, 정렬3으로 네이밍해주셔서 이대로 따라가는 방식을 선택해서 네이밍 한 결과입니다..!! 😃
<img width="272" alt="스크린샷 2022-01-16 오후 9 59 32" src="https://user-images.githubusercontent.com/46108770/149660959-8266c7a6-7572-4754-90b9-99427860f21e.png">
<img width="287" alt="스크린샷 2022-01-16 오후 9 59 40" src="https://user-images.githubusercontent.com/46108770/149660964-1653442d-89d7-428f-a380-642939fd04bb.png">
<img width="265" alt="스크린샷 2022-01-16 오후 9 59 46" src="https://user-images.githubusercontent.com/46108770/149660969-27b2f8aa-ec67-4a97-9dbc-c43f4bb4af9f.png">

더 좋은 이름이 생각이 안나는데 혹시 좋은 네이밍 있으면 추천 부탁드립니다!!

2022-01-16 13:17 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +           let view = UIView(frame: CGRect(x: 8.0, y: 8.0, width: actionSheet.view.bounds.size.width - 8.0 * 4.5, height: 120.0))
컬렉션뷰 셀 모양이 바뀌는걸 정렬이라고 네이밍했습니다!

2022-01-16 13:21 UTC, YoonAh-dev commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        case sort1, sort2, sort3
@beansbin 

Apple SFSymbol에 있는 아이콘들을 보면 네이밍을 이런식으로 하더라구요! 참고하셔서 네이밍하면 좋을 듯 합니다!
<img width="734" alt="스크린샷 2022-01-16 오후 10 02 02" src="https://user-images.githubusercontent.com/55099365/149661049-e7f823a1-485b-4deb-844d-c4864db1551f.png">

저도 제플린을 보면서 네이밍을 하긴하지만 코드로 쉽게 읽히지 않는 부분들은 읽기 쉬운 방식으로 네이밍을 변경해주는게 좋은 것 같아요!
정렬1, 정렬2, 정렬3 보다는 SFSymbol같은 네이밍이 어떤 state에 있는 확인하기에 더 좋을 거 같습니다.!

2022-01-16 13:33 UTC, sujinnaljin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +           let view = UIView(frame: CGRect(x: 8.0, y: 8.0, width: actionSheet.view.bounds.size.width - 8.0 * 4.5, height: 120.0))
정렬이라함은 보통 추천순, 인기순 카테고리 순 같이 아이템에 대한 정렬을 연상하기 쉬운 것 같아여
gridStyle 정도의 이름은 어떠실까여??? (근데 왜 여기에 정렬이라고 달았을까여??? 흠냐뤼)

2022-01-16 13:37 UTC, YoonAh-dev commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        present(bottomSheet, animated: true, completion: nil)
@beansbin 

뒷 배경 alpha를 투명하게 주고 위에 UIView를 얹은 형식으로 UIViewController가 BottomSheet로 뜬 거처럼 할 수 있습니다.!
생각보다 엄청 간단하고 원하는대로 커스텀할 수 있기 때문에 라이브러리보다 이점이 있지 않을까 싶네요!

2022-01-16 13:38 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        print("change!")
c0821291556aaa5d74e9760d3cc8a0f7b60a474c

2022-01-16 13:38 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        print("change!")
c0821291556aaa5d74e9760d3cc8a0f7b60a474c

2022-01-16 13:39 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
>      func setNavigationItems() {
c0821291556aaa5d74e9760d3cc8a0f7b60a474c

2022-01-16 13:39 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        super.viewWillAppear(animated)
navigation bar hidden = true로 적용시킬 때 필요했던 부분인 것 같은데 지금은 필요가 없어져서 삭제했습니다 !!
c0821291556aaa5d74e9760d3cc8a0f7b60a474c

2022-01-16 13:40 UTC, YoonAh-dev commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +           let view = UIView(frame: CGRect(x: 8.0, y: 8.0, width: actionSheet.view.bounds.size.width - 8.0 * 4.5, height: 120.0))
<img width="710" alt="스크린샷 2022-01-16 오후 10 33 14" src="https://user-images.githubusercontent.com/55099365/149662472-f0678e77-44a4-4bde-9090-914c51bf4d64.png">

CSS에서도 이런 모양을 GridStyle이라고 하는 걸 보니깐 gridStyle이라는 네이밍이 좋지 않을까 싶네요!?!

2022-01-16 13:40 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +    var sortNum: SortType = .sort1
정렬 형태를 의미하는 네이밍인데, sortType으로 네이밍 변경했습니다!
c0821291556aaa5d74e9760d3cc8a0f7b60a474c

2022-01-16 13:40 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        case sort1, sort2, sort3
2xN, 1xN 형태로 변경했습니다! :)
c0821291556aaa5d74e9760d3cc8a0f7b60a474c

2022-01-16 13:41 UTC, beansbin commented on Havit/Havit/Global/UIComponent/ContentsCollectionViewCell.swift
> +     private var mainImageView: UIImageView = {
c0821291556aaa5d74e9760d3cc8a0f7b60a474c

2022-01-16 13:41 UTC, beansbin commented on Havit/Havit/Coordinator/CategoryContentsCooridnator.swift
> +        case .main:
코멘트 주신대로 수정했습니다 :)
c0821291556aaa5d74e9760d3cc8a0f7b60a474c

2022-01-16 13:41 UTC, beansbin commented on Havit/Havit/Coordinator/AppCoordinator.swift
> +        let coordinator = CategoryContentsCoordinator(navigationController: navigationController)
c0821291556aaa5d74e9760d3cc8a0f7b60a474c

2022-01-16 13:43 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        present(bottomSheet, animated: true, completion: nil)
@sujinnaljin https://github.com/TeamHavit/Havit-iOS/pull/56#issuecomment-1013626089 이 부분 말씀하신게 맞나요 ..??!! navigation bar에서 내려오는 부분을 action sheet로 구현하라는 말씀하신걸까여 ????

2022-01-16 13:45 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        }
어제 윤아님이 설명해주신대로, register는 각 cell에 대해 한 번씩만 등록하도록 리팩토링했습니다!
c0821291556aaa5d74e9760d3cc8a0f7b60a474c

2022-01-16 13:46 UTC, beansbin commented
> 코드리뷰 변경사항에 대해서 커밋번호를 남겨주지 않으시면, 리뷰어가 처음부터 예빈님 파일을 다 봐야하는 이슈가 있습니다. 커밋번호를 남겨주세요. 그리고 레이아웃을 일단 대충만 잡아놓으신것 같은데, 리뷰어는 이게 제대로 된건지, 나중에 고칠 예정이시라 대충 처리해놓으신건지 알기 어렵습니다. 따라서 제대로 구현해주신 사항에 대해서만 커밋 및 pr 날려주시면 좋을 것 같습니다. +) 또한 접근자, 네이밍, let, var 선언 방식등 이전 pr 에 말씀드린 기본적인 부분이 제대로 적용되어있는 부분이 많아 의미있는 리뷰를 드리기 어려운 상황입니다 (약간,,린트봇 된 느낌,,,이랄까요,,) 이 부분들 제대로 확인후에 pr 날려주세요

이게 reply인가

2022-01-16 17:53 UTC, sujinnaljin commented on Havit/Havit.xcodeproj/project.pbxproj
> +		AAA1F7F1C6A54C8DE976C4C2 /* [CP] Check Pods Manifest.lock */ = {
요 파일이 남아있는 것으로 봐서 pod deinigrate 가 제대로 안된거 같은데 한번 더 확인해주실 수 있나용?_?

2022-01-16 18:03 UTC, beansbin commented on Havit/Havit.xcodeproj/project.pbxproj
> +		AAA1F7F1C6A54C8DE976C4C2 /* [CP] Check Pods Manifest.lock */ = {
bottomSheet 라이브러리 때문에 코코아팟 자체를 삭제하진 않았고 bt, bottomSheet 라이브러리 제거 및 관련 코드만 삭제한 상태입니다!

2022-01-16 18:06 UTC, sujinnaljin commented on Havit/Havit.xcodeproj/project.pbxproj
> +		AAA1F7F1C6A54C8DE976C4C2 /* [CP] Check Pods Manifest.lock */ = {
혹시 bottom Sheet 라이브러리까지 포함해서 다 삭제후에 그건 다른 pr 로 빼주시면 혹시 너무 오래 예빈님께 부담이 될까요???

2022-01-17 02:12 UTC, beansbin commented on Havit/Havit.xcodeproj/project.pbxproj
> +		AAA1F7F1C6A54C8DE976C4C2 /* [CP] Check Pods Manifest.lock */ = {
이미 gitignore에 pods가 들어간 develop을 merge한 상태에서 그게 가능할까요..?? ㅠㅠ bottomSheet 라이브러리는 삭제된 상태이고 코코아팟만 init된 상태입니당

일단 코코아팟 삭제해서 push 해두었습니닷!!!

2022-01-17 09:19 UTC, sujinnaljin commented on Havit/Havit.xcodeproj/project.pbxproj
> +		AAA1F7F1C6A54C8DE976C4C2 /* [CP] Check Pods Manifest.lock */ = {
gitignore에 pods가 들어간 develop을 merge한 상태 -> 요건 Pods 폴더가 있을 시 깃 파일에 무시한다는 얘기기 때문에 상관없을거 같아염!

2022-01-17 09:25 UTC, beansbin commented on Havit/Havit.xcodeproj/project.pbxproj
> +		AAA1F7F1C6A54C8DE976C4C2 /* [CP] Check Pods Manifest.lock */ = {
고럼 확인 후 어푸루브 해주시면 다음 pr에서  액션시트, 바텀 시트 구현하겠습니당!!

2022-01-17 09:32 UTC, noah0316 requested changes
빈스빈 선배!! SwiftLint 적용이 빠져있는 것 같은데 확인 한번 부탁드립니다~!!!!

2022-01-17 09:32 UTC, noah0316 commented on Havit/Havit.xcodeproj/project.pbxproj
> -		};
@beansbin 
p1;
예빈님 저 열심히 넣어놨는데.. 저 웁니다...🥺

2022-01-17 09:32 UTC, noah0316 commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        case sort, sort2xN, sort1xN
@beansbin 
p3;
혹시 sort 라는 네이밍이 swift array에서 제공하는 [sort](https://developer.apple.com/documentation/swift/array/1688499-sort)키워드와
네이밍이 겹쳐서 혼란을 줄 수 있을 것 같은데 [요기](https://github.com/TeamHavit/Havit-iOS/pull/56/files#r785442907)서 얘기 나왔던 grid와 관련된 것으로 네이밍을 변경해보는 것은 어떨까요?!

2022-01-17 09:34 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +           let view = UIView(frame: CGRect(x: 8.0, y: 8.0, width: actionSheet.view.bounds.size.width - 8.0 * 4.5, height: 120.0))
저도 정렬이라고 표현하는게 맘에 안들던 차에.. 참고자료 감사합니다..~~

2022-01-17 09:59 UTC, beansbin commented on Havit/Havit.xcodeproj/project.pbxproj
> -		};
아아앗 넣어놓았습니다.. 하하..... 감사합니다........😂
46e00f73c6f8adb633b2207e40e9bfea21a3e16c

2022-01-17 09:59 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +        case sort, sort2xN, sort1xN
반영했습니다! ^-^
46e00f73c6f8adb633b2207e40e9bfea21a3e16c

2022-01-17 10:01 UTC, sujinnaljin commented on Havit/Havit.xcodeproj/project.pbxproj
> -		};
어엇,,, 저 커밋에 없는것 같은데용,,!!! 린트 설정이 사라진거 같아용!!

2022-01-17 10:07 UTC, sujinnaljin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +            contentsCollectionView.register(cell: CategoryContents2xNCollectionViewCell.self)
이거 tab 할때마다 register 되는거 같은데, 저번에 윤아선배가 말씀주셔서 수정되었던 사항 아니었나여>>????

2022-01-17 10:10 UTC, beansbin commented on Havit/Havit/Screens/CategoryContents/View/CategoryContentsViewController.swift
> +            contentsCollectionView.register(cell: CategoryContents2xNCollectionViewCell.self)
어어 이상하다.. 제 로컬에는 그 코드가 없어진지 오래인데.. 지금도 확인해보니 없는데.. ?!!!! 뭐지.. push 다시 한번 날려볼게요~!

2022-01-17 10:16 UTC, beansbin commented on Havit/Havit.xcodeproj/project.pbxproj
> -		};
오잉... ? 근데 로컬에서 린트가 잘 돌아가고 있는 상태입니다.......... 어어...

2022-01-17 13:16 UTC, YoonAh-dev approved these changes
아자아자 빈스빈!!!!💜🗂

2022-01-17 13:17 UTC, noah0316 commented on Havit/Havit.xcodeproj/project.pbxproj
> -		};
@beansbin 
git hook의 pre-commit만 작동하고 있는 상태아닐까요...?!
혹시 Build Phases에 SwiftLint랑 pre-commit이 적용되었는지 확인해보실 수 있을까요???
<img width="1171" alt="BuildPhases" src="https://user-images.githubusercontent.com/63908856/149760643-ebe3c7aa-1f28-4f25-bf9b-2f2e5bcbe345.png">

<img width="871" alt="Screen Shot 2022-01-17 at 22 11 32" src="https://user-images.githubusercontent.com/63908856/149775739-423357b0-eed6-4d37-9002-4b5876b6d8fe.png">

2022-01-17 13:22 UTC, beansbin commented on Havit/Havit.xcodeproj/project.pbxproj
> -		};
![스크린샷 2022-01-17 오후 10 20 29](https://user-images.githubusercontent.com/46108770/149776409-c031dd00-14ad-4aa0-8ca6-38b87254260d.png)
![스크린샷 2022-01-17 오후 10 21 19](https://user-images.githubusercontent.com/46108770/149776518-f263d03e-d3f2-4212-9255-51fb85862818.png)

적용되어있는 것으로 확인됩니다! 🥲  @noah0316

2022-01-17 13:26 UTC, sujinnaljin approved these changes
고생꽐~!

2022-01-17 13:28 UTC, beansbin commented on Havit/Havit.xcodeproj/project.pbxproj
> -		};
![스크린샷 2022-01-17 오후 10 26 38](https://user-images.githubusercontent.com/46108770/149777307-e4dcc106-b122-48ff-be6f-5fe80a4a675d.png)
![스크린샷 2022-01-17 오후 10 26 54](https://user-images.githubusercontent.com/46108770/149777354-abca21fa-5176-4924-a29b-77e26267bb30.png)
@noah0316 요렇게 똑같이 뜹니다 !!

2022-01-17 13:30 UTC, noah0316 commented on Havit/Havit.xcodeproj/project.pbxproj
> -		};
아 넵 확인했습니다~!! :)

2022-01-17 13:30 UTC, noah0316 approved these changes

2022-01-17 13:30 UTC, noah0316 approved these changes
고생 선배~!!!!😊

2022-01-17 13:33 UTC, merged