[FEAT] SearchContentsView 레이아웃 및 UI Design
TeamHavit/Havit-iOS pull request #81
Opened 2022-01-17 06:14 UTC by beansbin

## 🟣 관련 이슈
- close #57 

## 🟣 구현/변경 사항 및 이유
- SearchContentsCoordinator 생성
- SearchContentsViewController 레이아웃 및 design 적용
- NotSearchedCollectionViewCell 구현
- 검색 버튼(엔터) 누르면 검색 결과 collectionView 나오도록 delegate 구현
- 취소 버튼 고정 및 function 연결

## 🟣  PR Point
* develop 브랜치에서 따와서 categoryContentsView와는 전혀 관련 없는! 코드이니 안심하시길..

## 🟣 참고 사항

https://user-images.githubusercontent.com/46108770/149951000-63d57657-f41d-48e9-91db-2b3999c15d78.mov

2022-01-17 08:32 UTC, YoonAh-dev commented on Havit/Havit/Coordinator/NotSearchedCollectionViewCell.swift
> +import UIKit
p1;

SnapKit import 해주세요!

2022-01-17 08:33 UTC, YoonAh-dev commented on Havit/Havit/Coordinator/NotSearchedCollectionViewCell.swift
> +        contentView.addSubview(imageView)
p2;

```swift
contentView.addSubViews([imageView, label])
```
이런식으로 한 데 묶어주세요!

2022-01-17 08:34 UTC, YoonAh-dev commented on Havit/Havit/Coordinator/NotSearchedCollectionViewCell.swift
> +            $0.top.equalTo(imageView).inset(-70)
p3;

inset으로 잡아도 좋지만, inset은 전체 화면에서 안쪽으로 잡는 느낌이라서 imageView와 label의 사이는 offset으로 간격을 잡아주는 게 좋을 거 같아요.!

2022-01-17 08:36 UTC, YoonAh-dev commented on Havit/Havit/Coordinator/NotSearchedCollectionViewCell.swift
> +    let label: UILabel = {
p1;

label보다는 어떤label인지 확실하게 네이밍해주면 이해하기 좋을 거 같아요! 
저도 네이밍을 못하기 때문에 적절한 예시일지 모르겠지만 noResultLabel이라던지.. 요런 느낌으로..?

2022-01-17 08:37 UTC, YoonAh-dev commented on Havit/Havit/Coordinator/SearchContentsCoordinator.swift
> +        case pop
p4;

저번에 보니깐 뒤로 가는 프로세스를 previous로 coordinator에서 맞춘 거 같더라구요.
예빈님도 previous로 맞춰보시는건 어떠신가용?

2022-01-17 08:45 UTC, YoonAh-dev commented on Havit/Havit/Screens/SearchContents/View/SearchContentsViewController.swift
> +        case before, result, empty
p4;

result는 어떤 state를 말하는 건지 느껴지는데 before와 empty는 어떤 state를 정확하게 말하는지 모르겠어요! 제 생각엔 검색전과 검색했는데 결과가 없는걸로 생각이 되는데.. 저도 네이밍을 못해서 .. . 딱히 생각이 안나지만 조금 더 직관적이었으면 좋겠다는 생각이 듭니당. 근데 저만 그런 걸수도 있어서 ..  다른 분들은 안그렇다고 하믄. . 넘어가셔도 ok...

2022-01-17 09:16 UTC, YoonAh-dev commented
@beansbin 

예빈님 혹시 시뮬 키보드로 검색하는 플로우로 한 번만 더 영상 찍어주실 수 있나용..?🥺

2022-01-18 09:10 UTC, Suyeon9911 commented on Havit/Havit/Coordinator/NotSearchedCollectionViewCell.swift
> +        label.font = UIFont.font(FontName.pretendardMedium, ofSize: CGFloat(14))
font 설정해줄 떄 그냥 .pretendardMedium 만 해줘도 됩니당 !!

2022-01-18 09:11 UTC, Suyeon9911 commented on Havit/Havit/Global/Resource/Assets.xcassets/imgSearchIs.imageset/Contents.json
> +  }
이미지 추가는 따로 풀리퀘 부탁드립니다 ! !ㅂ

2022-01-18 09:13 UTC, Suyeon9911 commented on Havit/Havit/Screens/SearchContents/View/SearchContentsViewController.swift
> +        case before, result, empty
@YoonAh-dev  저도 동의 합니다!! .. 딱 봤을때 어떤 state 인지 명확하게 해주시면 좋을 것 같습니다 !!

2022-01-18 09:14 UTC, sujinnaljin commented on Havit/Havit/Screens/SearchContents/View/SearchContentsViewController.swift
> +            DispatchQueue.main.async {
왜 요부분을 DispatchQueue.main.async 에 일일이 넣어주신걸까여?!?

2022-01-18 09:23 UTC, Suyeon9911 commented on Havit/Havit/Screens/SearchContents/View/SearchContentsViewController.swift
> +
혹시 viewDidLayoutSubviews 를 사용하신 이유가 있을까요?? 여기서 해주신 이유가 있으신가여 ??

2022-01-18 13:47 UTC, beansbin commented on Havit/Havit/Global/Resource/Assets.xcassets/imgSearchIs.imageset/Contents.json
> +  }
넵 다음 작업부터는 별도 pr로 올릴게요 ! !

2022-01-18 13:49 UTC, beansbin commented on Havit/Havit/Screens/SearchContents/View/SearchContentsViewController.swift
> +            DispatchQueue.main.async {
@sujinnaljin  DispatchQueue.main.async 내부에 쓰인 코드가 UI를 건드리는 코드라 메인 스레드에서 동작해야하기 때문에 넣어주었어여. 아니면 변경이 안되더라구요 흑흑

2022-01-18 13:53 UTC, beansbin commented on Havit/Havit/Screens/SearchContents/View/SearchContentsViewController.swift
> +
@Suyeon9911 searchBar 아래의 border를 표시하기 위해서입니다! 다른 함수에서 작업할 경우 라인이 안 보이는 경우가 있기 때문에 모든 레이아웃 작업이 완료된 후 가장 마지막에 호출되는 함수인 viewDidLayoutSubviews()에 작성해줌으로써 라인이 표시되는 것을 항상 보장하기 위해 사용했습니다 :)
[https://g-y-e-o-m.tistory.com/64](요기) 참고해서 작성했습니당~!

2022-01-18 13:55 UTC, beansbin commented on Havit/Havit/Coordinator/NotSearchedCollectionViewCell.swift
> +import UIKit
6441e7660bc

2022-01-18 13:55 UTC, beansbin commented on Havit/Havit/Coordinator/NotSearchedCollectionViewCell.swift
> +        contentView.addSubview(imageView)
6441e7660bc

2022-01-18 13:55 UTC, beansbin commented on Havit/Havit/Coordinator/NotSearchedCollectionViewCell.swift
> +            $0.top.equalTo(imageView).inset(-70)
6441e7660bc

2022-01-18 13:55 UTC, beansbin commented on Havit/Havit/Coordinator/SearchContentsCoordinator.swift
> +        case pop
6441e7660bc

2022-01-18 13:55 UTC, beansbin commented on Havit/Havit/Screens/SearchContents/View/SearchContentsViewController.swift
> +        case before, result, empty
6441e7660bc

2022-01-18 13:55 UTC, beansbin commented on Havit/Havit/Coordinator/NotSearchedCollectionViewCell.swift
> +        label.font = UIFont.font(FontName.pretendardMedium, ofSize: CGFloat(14))
6441e7660bc

2022-01-18 13:58 UTC, beansbin commented on Havit/Havit/Global/Resource/Assets.xcassets/imgSearchIs.imageset/Contents.json
> +  }
> @beansbin
> 
> 예빈님 혹시 시뮬 키보드로 검색하는 플로우로 한 번만 더 영상 찍어주실 수 있나용..?🥺

시뮬로 찍어서 재업로드 했습니닷!!

2022-01-18 14:27 UTC, YoonAh-dev commented on Havit/Havit/Screens/SearchContents/View/SearchContentsViewController.swift
> +        case before, result, empty
혹시 searchIng은 searching으로 해주실 수 있나유 .. . ?

2022-01-18 14:29 UTC, sujinnaljin commented on Havit/Havit/Screens/SearchContents/View/SearchContentsViewController.swift
> +
참고해주셨다고 하신 곳에서도 나와있지만 해당 함수는 한번만 호출되는게 아닙니다
아래와 같은 다양한 상황에서 해당 함수가 호출되므로, viewDidLayoutSubviews 에서 그때마다 객체를 생성하고 addSubView 를 해주면 이슈가 없을까요?
```
view의 크기나 위치 변경시 (ex. scroll, addSubView, frame이나 bound 에 value assign, 화면 로테이션 등)
- willlayoutSubview -> didLayoutSubview
view의 constraint 변경시 (ex. 버튼눌러서 constraint가 10에서 12로 변경 등)
- updateConstraint -> willlayoutSubview -> didLayoutSubview
```
해당 글 마지막에 적혀있는 아래의 처리가 되어있지 않고, 일부만 차용해주신 것 같아 커멘트 드립니다~
> 이 때는 저 border란 변수를 옵셔널 + 전역 변수로 선언하여 nil 체크를 하여 없을 때만 생성되게 하면 된다.

2022-01-18 14:31 UTC, sujinnaljin commented on Havit/Havit/Screens/SearchContents/View/SearchContentsViewController.swift
> +            DispatchQueue.main.async {
지금 저희 백그라운드에서 돌아가고 있는 코드가 있나요?
그리고 아래와 같이 처리해주면 cell 마다 감싸주지 않아도 되지 않을까여?
```swift
DispatchQueue.main.async {
  resultCollectionView.reloadData()
}
```

2022-01-18 14:54 UTC, beansbin commented on Havit/Havit/Screens/SearchContents/View/SearchContentsViewController.swift
> +            DispatchQueue.main.async {
오호라 이렇게 쓰는 방법도 있네요..👍  셀마다 queue 지우고 수정했습니다!!
![스크린샷 2022-01-18 오후 11 53 13](https://user-images.githubusercontent.com/46108770/149960670-821be93c-d680-4e8c-b576-57cf577cefa5.png)
![스크린샷 2022-01-18 오후 11 53 22](https://user-images.githubusercontent.com/46108770/149960703-3c1312b8-b30c-471d-814c-d23e3d1259e3.png)

2022-01-18 14:59 UTC, beansbin commented on Havit/Havit/Screens/SearchContents/View/SearchContentsViewController.swift
> +
> 이 때는 저 border란 변수를 옵셔널 + 전역 변수로 선언하여 nil 체크를 하여 없을 때만 생성되게 하면 된다.

border가 움직이는게 아니라 보이는거에 문제는 없다고 생각해서 해당 부분 처리는 해주지 않았습니다! ( 그래서 이거랑 별개로 스크롤에 따라 서치바가 움직이는 카테고리컨텐츠 뷰에서는 적용해주었습니당)
그런데 수진님 말씀 듣고 보니 객체를 매번 생성하는게 이슈를 일으킬 여지가 없을 수가 없단 생각이 들어서.. 🤔  마찬가지로 처리를 해줘야할 것 같네여! 정확한 지적 감사합니다! 💜

2022-01-18 15:09 UTC, Suyeon9911 approved these changes

2022-01-18 15:36 UTC, beansbin commented on Havit/Havit/Screens/SearchContents/View/SearchContentsViewController.swift
> +
00c700170872

2022-01-18 15:36 UTC, beansbin commented on Havit/Havit/Screens/SearchContents/View/SearchContentsViewController.swift
> +        case before, result, empty
00c700170872

2022-01-18 15:38 UTC, beansbin commented on Havit/Havit/Screens/SearchContents/View/SearchContentsViewController.swift
> +            DispatchQueue.main.async {
c8f3920bc72a038

2022-01-18 15:45 UTC, sujinnaljin commented on Havit/Havit/Screens/SearchContents/View/SearchContentsViewController.swift
> +
p2;
border 이슈였으면 border 관련만 viewDidLayoutSubviews 에 넣는건 어떨까요?

2022-01-18 16:03 UTC, beansbin commented on Havit/Havit/Screens/SearchContents/View/SearchContentsViewController.swift
> +
@sujinnaljin textField에서 border 분리하니 오른쪽 rightView까지 사라져버리는데..ㅜㅜ border 코드 분리는 후에 시간이 되면 리팩토링하도록 하겠습니다...!
![스크린샷 2022-01-19 오전 1 03 02](https://user-images.githubusercontent.com/46108770/149973384-7c39d081-eba5-4439-9079-c5a87ef429d8.png)

2022-01-18 16:07 UTC, YoonAh-dev approved these changes
고생꽈리~💜

2022-01-18 17:12 UTC, noah0316 requested changes
고생하셨습니다 선배~~!!👍

2022-01-18 17:12 UTC, noah0316 approved these changes

2022-01-19 02:46 UTC, merged